spring.application.name=NightWalkGuardian
spring.datasource.url=jdbc:mysql://localhost:3306/night_walk_guardian?useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8080
twilio.account.sid=
twilio.auth.token=
twilio.phone.number=

#fast2sms.api.key=